spring.application.name=oxefood-api-ian

server.port=8080
spring.config.import=optional:file:.env[.properties]

# Datasource ( levantando a aplicação sem container )
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5435/oxefood
spring.datasource.username=postgres
spring.datasource.password=oxefood

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.generate-ddl=true

# --- CONFIGURAÇÕES DE E-MAIL (AULA 26) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seuemail@gmail.com
# Atenção: a senha abaixo deve ser uma "Senha de Aplicativo" gerada no painel do Google, não a sua senha normal!
spring.mail.password=suasenha
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- CONFIGURAÇÕES DE SEGURANÇA / JWT ---
# Chave secreta (deve ser longa e complexa para garantir segurança)
api.security.token.secret=OxeFoodApiSecretKeySuperSeguraIFPEJaboatao2026
# Tempo de expiração do token (Ex: 2 horas = 7200000 milissegundos)
api.security.token.expiration=7200000